name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Neovim
      uses: nvim-lua/setup-neovim@v1
      with:
        neovim-version: '0.8.0'
    
    - name: Install stylua
      run: |
        curl -L https://github.com/JohnnyMorganz/StyLua/releases/latest/download/stylua-linux.zip -o stylua.zip
        unzip stylua.zip
        sudo mv stylua /usr/local/bin/
        chmod +x /usr/local/bin/stylua
    
    - name: Lint Lua files
      run: |
        stylua --check lua/
    
    - name: Check Lua syntax
      run: |
        find lua/ -name "*.lua" -exec lua -c {} \;
